Repository julianxhokaxhiu/FFNx, pull requests merged in 2020-11, with the labels that each got.

#130 Fixed license boilerplate
  src/cfg.cpp
Labels: meta

#132 #129 Allow multiple extensions for external_sfx/music/voice
  misc/FFNx.toml
  src/audio.cpp
  src/audio.h
  src/audio/openpsf/openpsf.cpp
  src/cfg.cpp
  src/cfg.h
Labels: enhancement

#135 Fix extension list building
  src/audio.cpp
  src/cfg.cpp
Labels: bug
