Repository julianxhokaxhiu/FFNx, pull requests merged in 2021-12, with the labels that each got.

#317 60FPS: Fix horizontal camera rotation bug and refactor
  src/ff7.h
  src/ff7/camera.cpp
  src/ff7/defs.h
  src/ff7_data.h
  src/ff7_opengl.cpp
Labels: bug, enhancement

#320 FF7: fix crash for FR/DE/SP versions
  src/ff7.h
  src/ff7_data.h
  src/ff7_opengl.cpp
Labels: bug

#319 60FPS: Add 60 fps animation for enemy deaths, actor movement, and man…
  misc/FFNx.toml
  src/cfg.cpp
  src/cfg.h
  src/common.cpp
  src/ff7.h
  src/ff7/animations.cpp
  src/ff7/camera.cpp
  src/ff7/defs.h
  src/ff7_data.h
  src/ff7_opengl.cpp
  src/globals.h
  src/patch.h
Labels: enhancement

#322 Voice: Add backbone for voiced battle dialogue
  misc/FFNx.toml
  src/cfg.cpp
  src/cfg.h
  src/ff7.h
  src/ff7_data.h
  src/voice.cpp
Labels: enhancement

#323 FF8: fix crash on non-US versions when ff8_ssigpu_debug is enabled
  src/ff8_data.h
Labels: bug

#324 Voice: Improve battle voices support
  src/achievement.cpp
  src/achievement.h
  src/ff7.h
  src/ff7/menu.cpp
  src/ff7_data.h
  src/voice.cpp
Labels: enhancement

#327 Voice: Replace hash with dialog text as filename
  src/voice.cpp
Labels: enhancement

#331 Voice: Add voice support for display action/info
  src/ff7.h
  src/ff7/animations.cpp
  src/ff7/battle.cpp
  src/ff7/defs.h
  src/ff7_data.h
  src/ff7_opengl.cpp
  src/voice.cpp
Labels: enhancement

#334 FF7: customize minigame music
  src/music.cpp
Labels: enhancement
