Repository julianxhokaxhiu/FFNx, pull requests merged in 2022-02, with the labels that each got.

#377 FF7: Fixed field shadows in movies
  src/common_imports.h
  src/ff7.h
  src/ff7_data.h
  src/lighting.cpp
Labels: bug

#379 FF7Achievement: Fix bug of End of Part 1 achievement
  src/achievement.h
Labels: bug

#380 FF7: Fixed field shadow crash when changing game modes
  src/lighting.cpp
Labels: bug

#387 60FPS: Interpolate battle camera and 3D models
  src/ff7.h
  src/ff7/animations.cpp
  src/ff7/animations.h
  src/ff7_data.h
Labels: enhancement

#389 Voice: Fix BATTLE character action voices bugs
  src/audio.cpp
  src/common.cpp
  src/ff7/defs.h
  src/ff7/misc.cpp
  src/hext.cpp
  src/utils.h
  src/voice.cpp
Labels: bug

#391 Fix fd leaks which can cause 7th heaven memory leaks
  src/renderer.cpp
Labels: bug

#390 FF8: Fix load and save texture for VRAM textures + adding discerr.lzs texture
  docs/ff8/assets/ff8-vram-game-flow.png
  docs/ff8/assets/ff8-vram-to-tex.png
  docs/ff8/index.md
  docs/ff8/vram.md
  docs/index.md
  src/common.cpp
  src/ff8.h
  src/ff8/texture_packer.cpp
  src/ff8/texture_packer.h
  src/ff8/vram.cpp
  src/image/tim.cpp
  src/image/tim.h
Labels: bug, enhancement

#394 60FPS: Fix WORLDMAP wait frames in the script + Small fix of FF8
  src/ff7.h
  src/ff7/world.cpp
  src/ff7_data.h
Labels: bug

#396 60FPS: Fix battle target pointer animation speed and Death kill animation + Refactor a data structure
  src/ff7.h
  src/ff7/animations.cpp
  src/ff7_data.h
Labels: bug

#398 60FPS: Fix battle targeting glitch by removing unneeded patches
  src/ff7.h
  src/ff7/animations.cpp
  src/ff7_data.h
Labels: bug

#403 60FPS: Fix Great Glacier counter steps before fainting
  src/ff7/field.cpp
  src/movies.cpp
  src/movies.h
Labels: bug
