Repository julianxhokaxhiu/FFNx, pull requests merged in 2022-08, with the labels that each got.

#472 FF7Achievement: Fix crash during load save file for spanish version
  src/ff7_opengl.cpp
Labels: bug

#471 Changed aspect ratio variable to allow multiple modes
  misc/FFNx.toml
  src/cfg.cpp
  src/cfg.h
  src/common.cpp
  src/common.h
  src/renderer.cpp
Labels: enhancement

#476 Lighting: fixed visual glitch when enabling both lighting and anti-aliasing
  src/lighting.cpp
  src/renderer.cpp
  src/renderer.h
Labels: bug, enhancement

#477 Widescreen: Fix quad about water effect in CHOCOBO mode
  src/ff7.h
  src/ff7/battle.cpp
  src/ff7/widescreen.cpp
  src/ff7_data.h
Labels: enhancement

#478 Lighting: Fixed draw call order for framebuffer effects
  src/common.cpp
  src/common.h
  src/gl.h
  src/gl/deferred.cpp
  src/movies.h
  src/renderer.cpp
  src/renderer.h
  src/video/movies.cpp
  src/video/movies.h
Labels: bug, enhancement

#479 FF8: Fix crash at exit
  src/ff8/texture_packer.cpp
  src/ff8/vram.cpp
  src/ff8/vram.h
Labels: bug, enhancement

#480 60FPS: Fix FIELD and WORLD mode text box animation speed (opening, closing, next paging)
  Changelog.md
  src/ff7.h
  src/ff7/field.cpp
  src/ff7/world.cpp
  src/ff7_data.h
  src/voice.cpp
Labels: bug, enhancement

#482 Widescreen: Added config logic and zoom implementation
  CMakeLists.txt
  Changelog.md
  misc/FFNx.blit.frag
  misc/FFNx.blit.vert
  src/cfg.cpp
  src/cfg.h
  src/common.cpp
  src/ff7.h
  src/ff7/field.cpp
  src/ff7/widescreen.cpp
  src/ff7/widescreen.h
  src/ff7_data.h
  src/gl.h
  src/gl/deferred.cpp
  src/renderer.cpp
  src/renderer.h
Labels: enhancement

#484 Widescreen: Added logic to offset camera scrolling and minor other fixes
  Changelog.md
  src/ff7/field.cpp
  src/ff7/widescreen.cpp
  src/ff7/widescreen.h
  src/gl/deferred.cpp
  src/lighting.cpp
  src/renderer.cpp
Labels: enhancement

#485 Widescreen: Added logic for vertical offset in movies and other minor fixes
  Changelog.md
  src/ff7/field.cpp
  src/ff7/widescreen.cpp
  src/ff7/widescreen.h
  src/movies.cpp
  src/renderer.cpp
  src/renderer.h
Labels: enhancement

#486 FF7: Move vertical center hext into FFNx code as toml config option
  misc/FFNx.toml
  misc/hext/ff7/de/FFNx.FIELD.vertical_center.txt
  misc/hext/ff7/en/FFNx.FIELD.vertical_center.txt
  misc/hext/ff7/es/FFNx.FIELD.vertical_center.txt
  misc/hext/ff7/fr/FFNx.FIELD.vertical_center.txt
  src/cfg.cpp
  src/cfg.h
  src/common.cpp
  src/ff7/field.cpp
  src/ff7_opengl.cpp
  src/field.cpp
  src/gl/gl.cpp
  src/globals.h
  src/hext.cpp
  src/renderer.cpp
Labels: enhancement

#487 VSCode: Add launch config for attach process
  .vscode/launch.json
Labels: enhancement
