Repository julianxhokaxhiu/FFNx, pull requests merged in 2022-12, with the labels that each got.

#510 FF8: SFX external
  Changelog.md
  src/audio.cpp
  src/audio.h
  src/ff8.h
  src/ff8_data.cpp
  src/sfx.cpp
Labels: enhancement

#512 FF7: Fixed incorrect time cycle filter conditional
  misc/FFNx.frag
Labels: bug

#515 FF7: Fixed time cycle filter not applying in battle mode
  src/ff7/battle/menu.cpp
  src/ff7/time.cpp
Labels: bug, enhancement

#516 60FPS: Fix Climhazzard random crash on poisoned enemy
  Changelog.md
  src/ff7.h
  src/ff7/battle/animations.cpp
  src/ff7_data.h
Labels: bug

#517 FF7: Fixed time cycle filter applying over the action text box in battle mode
  src/ff7.h
  src/ff7/battle/defs.h
  src/ff7/battle/menu.cpp
  src/ff7_data.h
  src/ff7_opengl.cpp
Labels: bug, enhancement

#518 FF7: Added logic to update a month string variable for the time cycle system
  misc/FFNx.time.toml
  src/ff7/time.cpp
  src/ff7/time.h
Labels: enhancement
