Repository julianxhokaxhiu/FFNx, pull requests merged in 2022-04, with the labels that each got.

#427 FF8: Configure game path and data drive via FFNx.toml
  misc/FFNx.toml
  src/cfg.cpp
  src/cfg.h
  src/common.cpp
  src/ff8.h
  src/ff8_data.cpp
  src/ff8_opengl.cpp
  src/game_cfg.cpp
  src/game_cfg.h
Labels: enhancement

#428 FF8: more debug output + Fix crash
  misc/FFNx.toml
  src/cfg.cpp
  src/cfg.h
  src/common.cpp
  src/ff7_opengl.cpp
  src/ff8/vibration.cpp
  src/ff8_data.cpp
  src/patch.cpp
  src/patch.h
Labels: enhancement

#431 FF8: fix alpha in texture replacement + looking for localized textures
  src/common.cpp
  src/ff8/file.cpp
  src/ff8/file.h
  src/ff8/texture_packer.cpp
  src/ff8_opengl.cpp
  src/renderer.cpp
Labels: bug, enhancement

#432 FF7: Fix deadzone bug for XINPUT analog triggers
  src/ff7/misc.cpp
Labels: bug

#433 FF8: vibration fixes on worldmap + xinput fix on steam + horizon concert fixes
  src/audio.cpp
  src/audio.h
  src/audio/openpsf/openpsf.cpp
  src/audio/openpsf/openpsf.h
  src/common.cpp
  src/ff8.h
  src/ff8/vibration.cpp
  src/ff8_data.cpp
  src/ff8_opengl.cpp
  src/music.cpp
Labels: bug, enhancement

#436 60FPS: Fix death timer increment in BATTLE mode
  src/ff7.h
  src/ff7/animations.cpp
  src/ff7_data.h
Labels: bug

#438 60FPS: Fix Tonberry glitchy movement in battle
  src/ff7/animations.cpp
Labels: bug
