Repository julianxhokaxhiu/FFNx, pull requests merged in 2022-03, with the labels that each got.

#405 FF8: Direct mode
  misc/FFNx.toml
  src/ff8.h
  src/ff8/file.cpp
  src/ff8/file.h
  src/ff8_data.h
  src/ff8_opengl.cpp
Labels: enhancement

#408 60FPS: Fix new rotation steps index not starting from zero in specific situation
  src/ff7/field.cpp
Labels: bug

#409 60FPS: Rework the 60FPS rotation movement logic
  src/ff7/field.cpp
Labels: enhancement

#412 FF8 - Voice feature
  src/ff8.h
  src/ff8_data.h
  src/voice.cpp
Labels: enhancement

#413 SFX FF7: Fix highwind SFX type separation logic
  src/ff7.h
  src/ff7/world.cpp
  src/ff7_data.h
Labels: bug

#414 FF8 Steam: #329 fix chocobo world crash
  src/common.cpp
Labels: bug

#416 60FPS: Fix bug in Cid attack SFX
  src/ff7.h
  src/ff7/animations.cpp
  src/ff7_data.h
Labels: bug

#417 Feature/ff8 japan
  misc/hext/ff8/jp/FFNx.WORLD.fix_uv_coords.txt
  misc/hext/ff8/jp_nv/FFNx.WORLD.fix_uv_coords.txt
  src/cfg.cpp
  src/common.cpp
  src/common.h
  src/ff8.h
  src/ff8_data.cpp
  src/music.cpp
  src/patch.cpp
Labels: enhancement

#418 Updating changelog
  Changelog.md
  README.md
Labels: meta

#421 FF8: Fix vibration on field & more sensations
  src/audio/openpsf/openpsf.cpp
  src/common.cpp
  src/ff8.h
  src/ff8/vibration.cpp
  src/ff8_data.cpp
  src/ff8_opengl.cpp
  src/gamepad.cpp
  src/gamepad.h
  src/globals.h
  src/music.cpp
  src/vibration.cpp
  src/vibration.h
Labels: enhancement

#422 FF8: Vibration modding
  CMakeLists.txt
  misc/FFNx.toml
  misc/FFNx.vibrate.ff8.field.toml
  misc/FFNx.vibrate.ff8.world.toml
  src/cfg.cpp
  src/cfg.h
  src/ff8/vibration.cpp
  src/vibration.cpp
  src/vibration.h
Labels: enhancement

#423 FF8: vibration modding fix hash
  src/ff8.h
  src/ff8/vibration.cpp
  src/ff8_data.cpp
Labels: bug
