Repository julianxhokaxhiu/FFNx, pull requests merged in 2023-11, with the labels that each got.

#617 FF8: Add support for palette changes in external textures + optimizations
  Changelog.md
  docs/ff8/mods/external_textures.md
  src/common.cpp
  src/ff8.h
  src/ff8/mod.cpp
  src/ff8/mod.h
  src/ff8/texture_packer.cpp
  src/ff8/texture_packer.h
  src/ff8/vram.cpp
  src/ff8_data.cpp
  src/ff8_opengl.cpp
  src/image/image.cpp
  src/image/image.h
  src/image/tim.h
  src/renderer.cpp
  src/renderer.h
Labels: enhancement

#619 FF8: move maki patch to FFNx core + Fix for blue color in fire spells
  Changelog.md
  misc/hext/ff8/de/.gitkeep
  misc/hext/ff8/de/FFNx.WORLD.fix_uv_coords.txt
  misc/hext/ff8/de_nv/.gitkeep
  misc/hext/ff8/de_nv/FFNx.WORLD.fix_uv_coords.txt
  misc/hext/ff8/en/.gitkeep
  misc/hext/ff8/en/FFNx.WORLD.fix_uv_coords.txt
  misc/hext/ff8/en_eidos/.gitkeep
  misc/hext/ff8/en_eidos/FFNx.WORLD.fix_uv_coords.txt
  misc/hext/ff8/en_eidos_nv/.gitkeep
  misc/hext/ff8/en_eidos_nv/FFNx.WORLD.fix_uv_coords.txt
  misc/hext/ff8/en_nv/.gitkeep
  misc/hext/ff8/en_nv/FFNx.WORLD.fix_uv_coords.txt
  misc/hext/ff8/es/.gitkeep
  misc/hext/ff8/es/FFNx.WORLD.fix_uv_coords.txt
  misc/hext/ff8/es_nv/.gitkeep
  misc/hext/ff8/es_nv/FFNx.WORLD.fix_uv_coords.txt
  misc/hext/ff8/fr/.gitkeep
  misc/hext/ff8/fr/FFNx.WORLD.fix_uv_coords.txt
  misc/hext/ff8/fr_nv/.gitkeep
  misc/hext/ff8/fr_nv/FFNx.WORLD.fix_uv_coords.txt
  misc/hext/ff8/it/.gitkeep
  misc/hext/ff8/it/FFNx.WORLD.fix_uv_coords.txt
  misc/hext/ff8/it_nv/.gitkeep
  misc/hext/ff8/it_nv/FFNx.WORLD.fix_uv_coords.txt
  misc/hext/ff8/jp/.gitkeep
  misc/hext/ff8/jp/FFNx.WORLD.fix_uv_coords.txt
  misc/hext/ff8/jp_nv/.gitkeep
  misc/hext/ff8/jp_nv/FFNx.WORLD.fix_uv_coords.txt
  src/ff8.h
  src/ff8_data.cpp
  src/ff8_opengl.cpp
Labels: bug, enhancement

#625 Sound: Fixed a typo when reading sound configuration in FF7
  Changelog.md
  src/common.cpp
Labels: bug

#626 FF7: Fix a softlock when trying to change in-game Controller setting to "Normal"
  Changelog.md
  src/ff7.h
  src/ff7_data.h
  src/ff7_opengl.cpp
  src/sfx.cpp
Labels: enhancement

#627 FF7: Fix character naming screen not working correctly when Steam Input is enabled
  Changelog.md
  src/ff7_opengl.cpp
Labels: enhancement
