Repository julianxhokaxhiu/FFNx, pull requests merged in 2023-07, with the labels that each got.

#564 Research for WM + battle texture replacement
  .screens/ff8-worldmap-official-release-vs-ffnx.png
  Changelog.md
  README.md
  misc/FFNx.toml
  src/cfg.cpp
  src/cfg.h
  src/common.cpp
  src/ff8.h
  src/ff8/battle/stage.cpp
  src/ff8/battle/stage.h
  src/ff8/texture_packer.cpp
  src/ff8/texture_packer.h
  src/ff8/uv_patch.cpp
  src/ff8/uv_patch.h
  src/ff8/vram.cpp
  src/ff8_data.cpp
  src/ff8_opengl.cpp
  src/gl/special_case.cpp
  src/image/tim.cpp
  src/image/tim.h
  src/patch.cpp
Labels: enhancement

#575 Common: Rework Movies and Game color rendering
  CMakeLists.txt
  docs/mods/video_encoding_guide.md
  docs/readme.md
  misc/FFNx.common.sh
  misc/FFNx.frag
  misc/FFNx.lighting.frag
  misc/FFNx.post.frag
  misc/FFNx.toml
  misc/glut_ebu_to_ntscj.png
  misc/glut_ebu_to_srgb.png
  misc/glut_inverse_ntscj_to_ebu.png
  misc/glut_inverse_ntscj_to_smptec.png
  misc/glut_inverse_ntscj_to_srgb.png
  misc/glut_ntscj_to_srgb.png
  misc/glut_smptec_to_ntscj.png
  misc/glut_smptec_to_srgb.png
  misc/glut_srgb_to_ntscj.png
  src/cfg.cpp
  src/cfg.h
  src/common.cpp
  src/renderer.cpp
  src/renderer.h
  src/video/movies.cpp
Labels: enhancement

#582 Update README.md
  README.md
Labels: meta

#584 FF8: Add more overridable textures for Worldmap + fixes
  Changelog.md
  docs/ff8/mods/external_textures.md
  docs/ff8/readme.md
  docs/mods/external_textures.md
  docs/readme.md
  misc/FFNx.toml
  src/cfg.cpp
  src/cfg.h
  src/ff8.h
  src/ff8/texture_packer.cpp
  src/ff8/texture_packer.h
  src/ff8/vram.cpp
  src/ff8_data.cpp
  src/ff8_opengl.cpp
  src/image/tim.cpp
Labels: bug, enhancement

#585 60FPS: Fix las0_5 map softlock in FF7
  Changelog.md
  src/ff7/field/enter.h
  src/ff7/field/model.cpp
  src/ff7/field/model.h
Labels: bug
