Repository julianxhokaxhiu/FFNx, pull requests merged in 2023-09, with the labels that each got.

#587 FF7: Fix direct color
  Changelog.md
  src/common.cpp
  src/ff7/field/field.cpp
  src/ff7_opengl.cpp
Labels: enhancement

#588 FF8: Fix crash with external texture replacement
  Changelog.md
  src/ff8/texture_packer.cpp
  src/ff8/vram.cpp
Labels: bug

#590 Improve clarity of data_drive usage
  misc/FFNx.toml
Labels: meta

#592 30FPS: Fix crash conflict in FF7 with ESUI mod
  src/ff7/battle/animations.cpp
  src/patch.h
Labels: bug

#591 FF8: better tonberry compatibility
  Changelog.md
  src/ff8.h
  src/ff8/texture_packer.cpp
  src/ff8/texture_packer.h
  src/ff8/vram.cpp
  src/ff8_data.cpp
  src/music.cpp
  src/utils.cpp
  src/utils.h
Labels: enhancement

#593 60FPS: Fix char status menu rendering speed in FF7
  src/ff7.h
  src/ff7/battle/animations.cpp
  src/ff7/battle/menu.cpp
  src/ff7/battle/menu.h
  src/ff7_data.h
Labels: bug

#594 FF8: Fix battle stage texture dump + option to use music files from remastered
  Changelog.md
  misc/FFNx.toml
  src/cfg.cpp
  src/cfg.h
  src/ff8/battle/stage.cpp
  src/music.cpp
Labels: bug, enhancement

#596 Fix: Revert "30FPS: Fix crash conflict in FF7 with ESUI mod (#592)"
  src/ff7/battle/animations.cpp
  src/patch.h
Labels: bug

#597 FF7: Refactor 60FPS battle menu fix and fix ESUI compatibility
  src/ff7.h
  src/ff7/battle/animations.cpp
  src/ff7/battle/menu.cpp
  src/ff7/battle/menu.h
  src/ff7_data.h
  src/ff7_opengl.cpp
Labels: bug, enhancement

#598 FF8: External texture fixes
  Changelog.md
  src/common.cpp
  src/ff8.h
  src/ff8/texture_packer.cpp
  src/ff8/texture_packer.h
  src/ff8/vram.cpp
  src/ff8_data.cpp
Labels: enhancement

#599 Fix/ff8 black worldmap
  src/ff8/vram.cpp
Labels: bug

#600 FF8: Fix crash in non-US versions
  src/ff8/field/chara_one.cpp
  src/ff8_data.cpp
Labels: bug

#602 FF8: Fix crash from PR #601
  src/ff8/uv_patch.cpp
  src/ff8_data.cpp
  src/voice.cpp
  src/world.cpp
Labels: bug

#603 FF7: Fix Bahamut Zero and Supernova not displaying correctly with lighting
  Changelog.md
  src/gl/gl.cpp
Labels: enhancement

#604 FF7: Fix field shadows not displaying during FMV movies
  Changelog.md
  src/gl/deferred.cpp
Labels: bug

#607 FF7: Implemented GPU-based original game lighting that better matches PSX version
  Changelog.md
  misc/FFNx.frag
  misc/FFNx.lighting.frag
  misc/FFNx.lighting.sh
  misc/FFNx.lighting.toml
  misc/FFNx.lighting.vert
  misc/FFNx.toml
  misc/FFNx.vert
  src/cfg.cpp
  src/cfg.h
  src/common.cpp
  src/common.h
  src/common_imports.h
  src/ff7.h
  src/ff7/defs.h
  src/ff7/graphics.cpp
  src/ff7_data.h
  src/ff7_opengl.cpp
  src/gl.h
  src/gl/deferred.cpp
  src/gl/gl.cpp
  src/lighting.cpp
  src/lighting.h
  src/lighting_debug.cpp
  src/renderer.cpp
  src/renderer.h
Labels: enhancement

#612 FF7: Fixed minor shadow visual glitches occurring in some fields
  Changelog.md
  misc/FFNx.lighting.toml
  misc/FFNx.pcf.sh
  src/lighting.cpp
  src/lighting.h
  src/lighting_debug.cpp
Labels: bug, enhancement

#608 FF7: Added experimental 16:10 support
  Changelog.md
  misc/FFNx.toml
  src/common.cpp
  src/common.h
  src/ff7/battle/animations.cpp
  src/ff7/field/background.cpp
  src/ff7/field/enter.h
  src/ff7/field/field.cpp
  src/ff7/field/model.cpp
  src/ff7/field/utils.h
  src/ff7/widescreen.cpp
  src/ff7_opengl.cpp
  src/gl/special_case.cpp
  src/globals.h
  src/movies.cpp
  src/renderer.cpp
Labels: enhancement
