Repository julianxhokaxhiu/FFNx, pull requests merged in 2024-02, with the labels that each got.

#650 FF8: Various enhancements and fixes
  CMakeLists.txt
  Changelog.md
  src/common.cpp
  src/ff8.h
  src/ff8/mod.cpp
  src/ff8/mod.h
  src/ff8/texture_packer.cpp
  src/ff8_data.cpp
  src/ff8_opengl.cpp
  src/image/image.cpp
  src/image/image.h
  src/renderer.cpp
  src/renderer.h
  vcpkg.json
Labels: bug, enhancement

#651 FF7: Preserve world camera state when changing game modes
  Changelog.md
  src/ff7/world/camera.cpp
Labels: enhancement

#655 FF8: Update metadata file when a save file is created
  .github/workflows/build.ps1
  Changelog.md
  docs/ff8/mods/external_textures.md
  misc/FFNx.toml
  src/ff8.h
  src/ff8/mod.cpp
  src/ff8/texture_packer.cpp
  src/ff8/texture_packer.h
  src/ff8/vram.cpp
  src/ff8_data.cpp
  src/ff8_opengl.cpp
Labels: enhancement

#657 FF7: Fixed menu not working when using the buggy
  Changelog.md
  src/ff7/world/player.cpp
Labels: bug

#659 FF7: Fixed menu not working when using external worldmap mesh
  src/ff7/world/player.cpp
Labels: bug

#663 FF8: fix JP Steam crash
  Changelog.md
  src/ff8_data.cpp
  src/ff8_opengl.cpp
Labels: bug

#664 FF7: Fixed scripted camera clipping when widescreen enabled
  Changelog.md
  src/ff7/field/background.cpp
  src/ff7/widescreen.cpp
  src/ff7/widescreen.h
Labels: bug

#666 FF7: Fixed auto-run not working sometimes on diagonals
  Changelog.md
  src/ff7/misc.cpp
Labels: enhancement

#667 FF7: Fixed not being able to place the flags during snowstorm
  Changelog.md
  src/ff7/world/camera.cpp
  src/ff7/world/player.cpp
  src/ff7/world/world.cpp
Labels: bug

#658 FF8: vibration option in main menu
  Changelog.md
  src/ff8.h
  src/ff8/vibration.cpp
  src/ff8_data.cpp
Labels: enhancement

#670 FF8: Fix texture animation only partially animated
  misc/FF8.reg
  src/ff8/mod.cpp
  src/ff8/texture_packer.h
Labels: bug, enhancement

#671 FF8: Fix texture animation only partially animated - part 2
  Changelog.md
  src/ff8/mod.cpp
  src/ff8/mod.h
Labels: bug, enhancement
