Repository julianxhokaxhiu/FFNx, pull requests merged in 2025-06, with the labels that each got.

#803 FF7 60FPS: Fix escape magic animation speed to 15FPS
  src/ff7.h
  src/ff7/battle/animations.cpp
  src/ff7_data.h
Labels: bug, enhancement

#804 FF8: Accept input while game window is not focused
  misc/FFNx.toml
  src/cfg.cpp
  src/cfg.h
  src/ff8_opengl.cpp
Labels: enhancement

#806 FF8: Fix triple triad card index issue and achievements stuff
  src/ff8/save_data.h
  src/movies.cpp
  src/voice.cpp
Labels: bug
