Repository julianxhokaxhiu/FFNx, pull requests merged in 2025-07, with the labels that each got.

#810 FF7 60FPS: Fix escape magic animation speed to 60FPS
  src/ff7.h
  src/ff7/battle/animations.cpp
  src/ff7_data.h
Labels: bug

#820 Gardening: Update README.md for Neovim section
  README.md
Labels: meta

#822 FF8: Allow to load fs subarchives using direct_path
  Changelog.md
  src/ff8.h
  src/ff8/file.cpp
  src/ff8/file.h
  src/ff8_data.cpp
  src/ff8_opengl.cpp
Labels: enhancement

#821 FF8: Fix crashes in non-US versions
  src/ff8.h
  src/ff8_data.cpp
  src/ff8_opengl.cpp
Labels: bug

#827 FF8: Fix crashes in JP version
  Changelog.md
  src/ff8_data.cpp
  src/ff8_opengl.cpp
  src/field.cpp
Labels: bug
